<?php 
@define ('_tienganh','EN');
@define ('_loidonhang','Thông báo!, Hệ thống gửi đơn hàng lỗi');
@define ('_dathangthanhcong','Thông báo!, Đặt hàng thành công!!!.');
@define ('_banchochactieptuc','Bạn có chắc chắn tiếp tục');
@define ('_xacnhan','XÁC NHẬN');
@define ('_back','TRỞ LẠI');
@define ('_thoathuan','Thỏa thuận');
@define ('_giaship','Phí vận chuyển');
@define ('_chiphihanghoa','Chi phí hàng hóa');
@define ('_hoten','Họ Tên');
@define ('_xntt','XÁC NHẬN THANH TOÁN');
@define ('_dongia','Đơn giá');
@define ('_tieptucmua','Tiếp tục mua hàng');
@define ('_khongcosanpham','Không có sản phẩm nào trong giỏ');
@define ('_paymentcomplete','Thanh toán thành công');
@define ('_thanhtoan','Thanh toán');
@define ('_ghvtt','Giao hàng và thanh toán');
@define ('_cart','Giỏ hàng');
@define ('_vat','Đã bao gồm VAT nếu có');
@define ('_tamtinh','Tạm tính');
@define ('_ghichu','Ghi chú đơn hàng');
@define ('_phuongthucthanhtoan','Phương thức thanh toán');
@define ('_phuongthucgiaohang','Phương thức giao hàng');
@define ('_chontinhthanh','Chọn tỉnh thành');
@define ('_support','Hỗ Trợ');
@define ('_doctinmoi','Đọc Tin Tức Mới Nhất');
@define ('_xemthem','Xem Thêm');
@define ('_oficescoffee','Sản phẩm');
@define ('_mabaomat','Nhập mã bảo mật');
@define ('_tag','Tag');
@define ('_hotrokhachhang','HỖ TRỢ KHÁCH HÀNG');
@define ('_nhapsodienthoai','Nhập số điện thoại');
@define ('_conhang','Còn hàng');
@define ('_sanphamlienquan','SẢN PHẨM LIÊN QUAN');
@define ('_dangboi','Đăng bởi');
@define ('_hosonangluc','Hồ sơ năng lực');
@define ('_tintucvasukien','Tin Tức & Sự Kiện');
@define ('_cacmathangdathuchien','CÁC MẶT HÀNG ĐÃ THỰC HIỆN');
@define ('_lienhebanner','Liên hệ ngay');
@define ('_banner','Banner');
@define ('_xemvitri','Xem vị trí');
@define ('_nhapemailcuaban','Gửi mail ngay');
@define ('_danhmuc','DANH MỤC');
@define ('_visaochonquangming','VÌ SAO CHỌN QUANG MIN');
@define ('_bangmamau','BẢNG MÃ MÀU');
@define ('_timhieuvechungtoi','TÌM HIỂU VỀ CHÚNG TÔI');
@define ('_videoclip','VIDEO CLIP');
@define ('_baogia','Báo giá');
@define ('_bangmau','Bảng màu');
@define ('_emailtontaitronghethong','Email đã tồn tại trong hệ thống !!!');
@define ('_tacgia','TÁC GIẢ');
@define ('_chiase','Chia sẻ');
@define ('_khachhangnoigiveebi','KHÁCH HÀNG NÓI GÌ VỀ EBI');
@define ('_dangkynhantin','Đăng ký nhận tin');
@define ('_ketnoivoiebi','KẾT NỐI VỚI EBI');
@define ('_chitiet','Chi tiết');
@define ('_gioithieuve','GIỚI THIỆU VỀ');
@define ('_tukhoacantim','Từ khóa cần tìm');
@define ('_hotro','Hỗ Trợ');
@define ('_administrator','Administrator');
@define ('_cn','Tiếng trung');
@define ('_baivietkhac','Bài viết khác');
@define ('_sodienthoaitontaitronghethong','Số điện thoại đã tồn tại trong hệ thống!!!');
@define ('_guithongtinthatbai','Gửi thông tin thất bại');
@define ('_lienhethatbai','Liên hệ thất bại');
@define ('_guithudenchungtoi','Gửi thư đến chúng tôi');
@define ('_chiduong','Chỉ đường');
@define ('_chatfacebook','Chat Facebook');
@define ('_tienich','Tiện ích');
@define ('_hinhanhsanpham','HÌNH ẢNH SẢN PHẨM');
@define ('_giaidaphotrongaytucthi','Giải đáp hỗ trợ ngay tức thì');
@define ('_chatzalo','Chat zalo');
@define ('_thongtinchitiet','THÔNG TIN CHI TIẾT');
@define ('_yeucaugoilai','Yêu cầu gọi lại');
@define ('_dangcapnhat','Đang cập nhật...');
@define ('_phantrangsanpham','Phân trang sản phẩm');
@define ('_chinhsachquidinh','QUI ĐỊNH & CHÍNH SÁCH');
@define ('_doitaccua','ĐỐI TÁC CỦA');
@define ('_congtrinhnoibat','CÔNG TRÌNH NỔI BẬT');
@define ('_visaochonquangminh','VÌ SAO CHỌN KỆ SẮT QUANG MINH');
@define ('_guithongtinthanhcong','Gửi thông tin thành công!!!');
@define ('_mabaomatkhongdung','Mã bảo mật không đúng');
@define ('_macapcha','Mã capcha');
@define ('_noidungdangcapnhat','Nội dung đang cập nhật...');
@define ('_xemchitiet','LIÊN HỆ NGAY');
@define ('_xemthem','XEM THÊM');
@define ('_xemtrenbando','Xem trên bản đồ');
@define ('_boiadmin','BỞI ADMIN');
@define ('_docthem','Đọc thêm');
@define ('_tintucmoi','Tin tức mới');
@define ('_vechungtoi','Về chúng tôi');
@define ('_lienketvoichungtoi','Liên kết với chúng tôi');
@define ('_chinhsach','Chính sách');
@define ('_thongtinvechungtoi','Thông tin về chúng tôi');
@define ('_timkiem','Tìm kiếm');
@define ('_lienhe','Liên hệ');
@define ('_home','Trang chủ');
@define ('_lienhengay','Liên hệ ngay chúng tôi');
@define ('_chatzalo','Chat với chúng tôi qua Zalo');
@define ('_goingay','Gọi ngay cho chúng tôi');
@define ('_guingay','Gửi ngay');
@define ('_chonquanhuyen','Chọn quận huyện');
@define ('_chonthanhpho','Chọn thành phố');
@define ('_chonphuongxa','Chọn phường xã');
@define ('_nhapdienthoai','Nhập số điện thoại');
@define ('_giamgia','Giảm giá');
@define ('_sanphamlienquan','Sản phẩm liên quan');
@define ('_noidungchitiet','Nội dung chi tiết');
@define ('_total','Tổng truy cập');
@define ('_online','Đang online');
@define ('_ketnoi','Kết nối với chúng tôi');
@define ('_all','Tất cả');
@define ('_themvaogio','Thêm vào giỏ');
@define ('_ketqua','Kết quả');
@define ('_co','Có');
@define ('_tukhoa','Từ khóa');
@define ('_gui','Gửi');
@define ('_nhapnoidung','Nhập nội dung');
@define ('_guithongtin','Gửi thông tin cho chúng tôi');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_ketnoivoichungtoi','Kết nối với chúng tôi');
@define ('_doitac','Đối tác');
@define ('_congtrinhnoibat','Công trình nổi bật');
@define ('_xemthem','Xem thêm');
@define ('_dichvucuachungtoi','Dịch vụ của chúng tôi');
@define ('_album','Hình ảnh');
@define ('_tuan','Tuần');
@define ('_nhantinface','Nhắn tin facebook');
@define ('_huongdanduongdi','Hướng dẫn đường đi');
@define ('_guithuden','Gửi thư đến');
@define ('_send','Gửi');
@define ('_sanphamcungloai','Sản phẩm cùng loại');
@define ('_chitietsanpham','Chi tiết sản phẩm');
@define ('_tong','Tổng');
@define ('_thang','Tháng');
@define ('_ngay','Ngày');
@define ('_nhaptukhoa','Nhập từ khóa');
@define ('_baivietlienquan','Bài viết liên quan');
@define ('_chinhsachquydinh','Chính sách & quy định');
@define ('_danhgiakhachhang','Đánh giá khách hàng');
@define ('_tintucnoibat','Tin tức nổi bật');
@define ('_visaochonchungtoi','Vì sao chọn chúng tôi');
@define ('_dichvunoibat','Dịch vụ nổi bật');
@define ('_uploadfile','Tải file');
@define ('_ngaytao','Ngày tạo');
@define ('_ten','Họ và Tên ');
@define ('_quanlylienhe','Quản lý liên hệ');
@define ('_tuyendung','Tuyển dụng');
@define ('_dichvu','Dịch vụ');
@define ('_danhsach','Danh sách');
@define ('_tenbien','Tên biến');
@define ('_quangcao','Quảng cáo');
@define ('_duan','Dự án');
@define ('_tintuc','Tin tức');
@define ('_sanpham','Sản phẩm');
@define ('_xemlichdangky','Xem lịch đăng ký');
@define ('_thongtinthanhtoan','Thông tin thanh toán');
@define ('_thaydoimatkhau','Thay đổi mật khẩu');
@define ('_hoidap','Hỏi đáp');
@define ('_nhanxetcuatoi','Nhận xét của tôi');
@define ('_sanphammuasau','Sản phẩm mua sau');
@define ('_sanphamyeuthich','Sản phẩm yêu thích');
@define ('_sanphamdaxem','Sản phẩm đã xem');
@define (' _thongtinthanhtoan','Thôn tin thanh toán');
@define ('_thaydoithongtin','Thay đổi thông tin');
@define ('_quanlythongtincanhan','Quản lý thông tin cá nhân');
@define ('_thongtincanhan','Thông tin cá nhân');
@define ('_huongdanmuahang','Hướng dẫn mua hàng');
@define ('_chualathanhvien','Chưa là thành viên');
@define ('_dangnhapwebsite','Đăng nhập website');
@define ('_chinhsachbaomat','Chính sách bảo mật');
@define ('_dieukhoansudung','Điều khoản sử dụng');
@define ('_thongtinbatbuoc','Thông tin bắt buộc');
@define ('_dangkyngay','Đăng ký ngay');
@define ('_nhapsodienthoai','Nhập số điện thoại');
@define ('_nhaphoten','Nhập họ tên');
@define ('_nhapemail','Nhập email');
@define ('_nu','Nữ');
@define ('_nam','Nam');
@define ('_ngaysinh','Ngày sinh');
@define ('_taiday','tại đây');
@define ('_dangnhap','Đăng nhập');
@define ('_dalathanhvien','Đã là thành viên');
@define ('_dangkywebsite','Đăng ký thành viên');
@define ('_dangkythanhvien','Đăng ký thành viên');
@define ('_thuoctinh','Thuộc tính');
@define ('_motangan','Mô tả ngắn');
@define ('_thongtinthem','Thông tin thêm');
@define ('_thanhtien','Thành tiền');
@define ('_tensanpham','Tên sản phẩm');
@define ('_yeucauthem','Yêu cầu thêm');
@define ('_quanhuyen','Quận huyện');
@define ('_tinhthanh','Tỉnh thành');
@define ('_thongtinnguoimua','Thông tin người mua');
@define ('_thongtindonhang','Thông tin đơn hàng');
@define ('_xemvasuadonhang','Xem và sửa đơn hàng');
@define ('_thoat','Thoát');
@define ('_thongkehedieuhanh','Thống kê hệ điều hành');
@define ('_tongtruycap','Tổng truy cập');
@define ('_hoantat','Hoàn tất');
@define ('_nhaplaimatkhau','Nhập lại mật khẩu');
@define ('_matkhaumoi','Mật khẩu mới');
@define ('_matkhau','Mật khẩu');
@define ('_tendangnhap','Tên đăng nhập');
@define ('_capnhatthongtin','Cập nhật thông tin');
@define ('_thongtintaikhoan','Thông tin tài khoản');
@define ('_hedieuhanh','Hệ điều hành');
@define ('_tyle','Tỉ lệ');
@define ('_luotxem','Lượt xem');
@define ('_trinhduyet','Trình duyệt');
@define ('_thongketrinhduyet','Thống kê trình duyệt');
@define ('_songuoitruycap','Số người truy cập');
@define ('_xemthongke','Xem thống kê');
@define ('_thongketheothang','Thống kê theo tháng');
@define ('_thongkethang','Thống kê tháng');
@define ('_stt','STT');
@define ('_tenhinh','Tên hình ảnh');
@define ('_links','Links');
@define ('_hientai','Hiện tại');
@define ('_hinhanhsagroup','Hình ảnh S.A Group');
@define ('_hinhanhquangcao','Hình quảnh cáo');
@define ('_sendmail','Send mail');
@define ('_filedinhkem','File đính kèm');
@define ('_quanlyemail','Quản lý email');
@define ('_quanly','Quản lý');
@define ('_update','Cập nhật');
@define ('_cauhinhwebsite','Cấu hình website');
@define ('_thietlaphethong','Thiết lập hệ thống');
@define ('_update liên Hệ','Update liên hệ');
@define ('_codebody','Code body');
@define ('_codehead','Code Annalytics');
@define ('_othercode','Othercode');
@define ('_hethongcuahang','Hệ thống cửa hàng');
@define ('_laymanhung','lấy mã nhúng');
@define ('_nhungiframe','Iframe maps');
@define ('_toadoweb','Tọa độ google maps');
@define ('_website','Trang website');
@define ('_sozalo','Số zalo');
@define ('_linkcontactweb','Liên kết trang website');
@define ('_linkmessage','Link messenger');
@define ('_hotline','Hotline');
@define ('_title1','Tiêu đề');
@define ('_vidu','Ví dụ');
@define ('_logout','Thoát');
@define ('_vaowebsite','Vào website');
@define ('_capnhatsitemap','Cập nhật sitemap');
@define ('_hello','Hello');
@define ('_menu','Menu');
@define ('_nhapgiatritheogiavietnam','Nhập giá trị theo giá Việt Nam');
@define ('_yennhat','Yên nhật');
@define ('_chuyendoitiente','Chuyển đổi tiền tệ');
@define ('_soluongphantrang','Số SP phân trang');
@define ('_thuoctinhcauhinh','Thuộc tính cấu hình');
@define ('_dangky','Gửi Ngay');
@define ('_motakhuyenmai','Mô tả khuyến mãi');
@define ('_trangthai','Trạng thái');
@define ('_giacu','Giá củ');
@define ('_loaisp','loại sản phẩm');
@define ('_masp','Mã sản phẩm');
@define ('_hinhdinhkem','Hình ảnh đính kèm');
@define ('_hinhanhdanhmuc','Hình ảnh danh mục');
@define ('_uploadhinhanh','Tải ảnh lên');
@define ('_hinhhientai','Hình hiện tại');
@define ('_hienthi','Hiển thị');
@define ('_sothutu','STT');
@define ('_kytutotnhat','Ký tự tốt nhất');
@define ('_kytu','Ký tự');
@define ('_description','Description');
@define ('_noidungseo','Nội dung SEO');
@define ('_keywords','Từ khóa');
@define ('_sua','Chỉnh sửa');
@define ('_danhsachreview','Danh sách review');
@define ('_noidung','Nội dung');
@define ('_mota','Mô tả');
@define ('_tiengviet','VN');
@define ('_thongtinchung','Thông tin chung');
@define ('_tieude','Tiêu đề');
@define ('_hinhanh','Hình ảnh');
@define ('_xemtheotinhtrangdonhang','Lọc theo tình trạng đơn hàng');
@define ('_moidat','Mới đặt');
@define ('_xuat','Xuất file');
@define ('_tinhtrang','Tình trạng');
@define ('_tongdonhang','Tổng đơn hàng');
@define ('_ngaydat','Ngày đặt');
@define ('_dienthoai','Số điện thoại');
@define ('_hoten','Họ và tên');
@define ('_xuatfile','Xuất file');
@define ('_ngayketthuc','Ngày kết thúc');
@define ('_chonngaybatdau','Chọn ngày bắt đầu');
@define ('_timkiemnangcao','Tìm kiếm nâng cao');
@define ('_tim','Tìm kiếm');
@define ('_sodienthoai','Số điện thoại');
@define ('_hovaten','Họ và tên');
@define ('_madonhang','Mã đơn hàng');
@define ('_xoa','Xóa');
@define ('_donhang','Đơn hàng');
@define ('_danhsach','Danh sách');
@define ('_thaotac','Chỉnh sửa');
@define ('_anhien','Ẩn hiện');
@define ('_noibat','Nổi bật');
@define ('_tendanhmuc','Tên danh mục');
@define ('_thutu','Thứ tự');
@define ('_nhaptukhoatimkiem','Nhập từ khóa tìm kiếm');
@define ('_xoachon','Xóa chọn');
@define ('_timkiem','Tìm kiếm');
@define ('_them','Thêm');
@define ('_tatca','Tất cả');
@define ('_hinhanhsharelink','Hình ảnh share link');
@define ('_cauhinhchung','Cấu hình chung');
@define ('_footer','Footer');
@define ('_thoigianlamviec','Thời gian làm việc');
@define ('_quanlydangky','Quản lý đăng ký');
@define ('_account','Tài khoản');
@define ('_popup','Pop up');
@define ('_backgroundfooter','Background footer');
@define ('_backgroundintroduce','Background introduce');
@define ('_backgroundsagroup','Background S.A Group');
@define ('_backgroundreview','Background review');
@define ('_quangcaotrongyoutube','Hình quảng cáo trong youtube');
@define ('_quangcaotrong4','Hình quảng cáo 4');
@define ('_quangcaotrong3','Hình quảng cáo 3');
@define ('_quangcaotrong2','Hình quảng cáo 2');
@define ('_quangcaotrong1','Hình quảng cáo 1');
@define ('_backgroundheader','Backgroud header');
@define ('_backgroundtop','Background top');
@define ('_logo','Hình logo');
@define ('_hinhvisa','Hình ảnh visa');
@define ('_hinhanhmxh','Hình ảnh mạng xã hội');
@define ('_thongbao','Thông báo');
@define ('_vaowebiste','Vào webiste');
@define ('_hinhanhslider','Hình ảnh slider');
@define ('_gioithieu','Giới thiệu');
@define ('_ngonngu','Ngôn ngữ');
@define ('_hotrongonngu','Hổ trợ ngôn ngữ');
@define ('_taikhoanadmin','Tài khoản admin');
@define ('_thongtin','Thông tin');
@define ('_hinhanhwebsite','Hình ảnh website');
@define ('_slider','SLIDER');
@define ('_video','VIDEO');
@define ('_trangtinh','Trang tĩnh');
@define ('_baivietchung','Bài viết chung');
@define ('_danhsachdonhang','Danh sách đơn hàng');
@define ('_donhangdahuy','Đơn hàng đã hủy');
@define ('_donhangdagiao','Đơn hàng đã giao');
@define ('_donhangdanggiao','Đơn hàng đang giao');
@define ('_donhangdaxacnhan','Đơn hàng đã xác nhận');
@define ('_donhangmoidat','Đơn hàng mới đặt');
@define ('_quanlysanpham','Quản lý sản phẩm');
@define ('_danhmuccap3','Danh mục cấp 3');
@define ('_danhmuccap2','Danh mục cấp 2');
@define ('_order','đặt hàng');
@define ('_danhmuccap1','Danh mục cấp 1');
@define ('_contactus','Liên hệ');
@define ('_banmuontimkiemsanpham','Bạn cần tím kiếm gì nào?');
@define ('_listview','List view');
@define ('_buynow','Mua ngay');
@define ('_khuyenmaidacbiet','Khuyến mãi đặc biệt');
@define ('_giaban','Giá bán');
@define ('_soluong','Số lượng');
@define ('_hansudung','Hạn sử dụng');
@define ('_thuonghieu','Thương hiệu');
@define ('_xuatxu','Xuất xứ');
@define ('_dungtich','Dung tích');
@define ('_loaisanpham','Loại sản phẩm');
@define ('_productinfo','Thông tin sản phẩm');
@define ('_storesagroup','Store SA Group');
@define ('_servicepolicy','Dịch vụ & chính sách');
@define ('_contacinfomation','Thông tin liên lạc');
@define ('_customcare','Chăm sóc khách hàng');
@define ('_readmore','Đọc thêm');
@define ('_about','About');
@define ('_gotosee','Go to see');
@define ('_gotofollow','Go to follow');
@define ('_review','Review');
@define ('_categorybest','Sản phẩm tốt nhất');
@define ('_contact','Liên hệ');
@define ('_news','TIN TỨC');
@define ('_email','Email');
@define ('_phone','Hotline');
@define ('_diachi','Địa chỉ');
@define ('_lienhevoichungtoi','Liên hệ với chúng tôi');
?>